version: '3'
services:
  drupal:
    image: drupal
    ports:
      - "8080:80"
    volumes:
      - ./drupal/modules:/var/www/html/modules
      - ./drupal/profiles:/var/www/html/profiles
      - ./drupal/themes:/var/www/html/themes
      - ./drupal/sites:/var/www/html/sites
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql
