version: '3'
services:
  prestashop:
    image: prestashop/prestashop:latest
    ports:
      - "8081:80"
    volumes:
      - ./prestashop:/var/www/html
    environment:
      - DB_SERVER=db
      - DB_USER=prestashop
      - DB_PASSWORD=prestashop
      - DB_NAME=prestashop

    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/data:/var/lib/mysql
